[workspace]

members = [
  "shared",
  "ledger",
  "price-server",
  "cli",
  "hedging",
  "user-trades",
  "okex-price",
  "okex-client",
  "bitfinex-client",
  "bitfinex-price",
  "galoy-client",
  "kollider-price",
]
